# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\tools\pw_scriptEditor\widgets\scriptEditor.ui'
#
# Created: Mon Mar 16 11:15:50 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_scriptEditor(object):
    def setupUi(self, scriptEditor):
        scriptEditor.setObjectName(_fromUtf8("scriptEditor"))
        scriptEditor.resize(800, 600)
        self.centralwidget = QtGui.QWidget(scriptEditor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.frame_2)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.executeAll_btn = QtGui.QPushButton(self.frame)
        self.executeAll_btn.setObjectName(_fromUtf8("executeAll_btn"))
        self.horizontalLayout_2.addWidget(self.executeAll_btn)
        self.clearHistory_btn = QtGui.QPushButton(self.frame)
        self.clearHistory_btn.setObjectName(_fromUtf8("clearHistory_btn"))
        self.horizontalLayout_2.addWidget(self.clearHistory_btn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.splitter = QtGui.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.out_ly = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.out_ly.setMargin(0)
        self.out_ly.setObjectName(_fromUtf8("out_ly"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.in_ly = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.in_ly.setMargin(0)
        self.in_ly.setObjectName(_fromUtf8("in_ly"))
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame_2)
        scriptEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(scriptEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.theme_menu = QtGui.QMenu(self.menuOptions)
        self.theme_menu.setObjectName(_fromUtf8("theme_menu"))
        scriptEditor.setMenuBar(self.menubar)
        self.executeAll_act = QtGui.QAction(scriptEditor)
        self.executeAll_act.setObjectName(_fromUtf8("executeAll_act"))
        self.clearHistory_act = QtGui.QAction(scriptEditor)
        self.clearHistory_act.setObjectName(_fromUtf8("clearHistory_act"))
        self.save_act = QtGui.QAction(scriptEditor)
        self.save_act.setObjectName(_fromUtf8("save_act"))
        self.load_act = QtGui.QAction(scriptEditor)
        self.load_act.setObjectName(_fromUtf8("load_act"))
        self.exit_act = QtGui.QAction(scriptEditor)
        self.exit_act.setObjectName(_fromUtf8("exit_act"))
        self.openManual_act = QtGui.QAction(scriptEditor)
        self.openManual_act.setObjectName(_fromUtf8("openManual_act"))
        self.quickHelp_act = QtGui.QAction(scriptEditor)
        self.quickHelp_act.setObjectName(_fromUtf8("quickHelp_act"))
        self.saveSeccion_act = QtGui.QAction(scriptEditor)
        self.saveSeccion_act.setObjectName(_fromUtf8("saveSeccion_act"))
        self.tabToSpaces_act = QtGui.QAction(scriptEditor)
        self.tabToSpaces_act.setObjectName(_fromUtf8("tabToSpaces_act"))
        self.spacesToTabs_act = QtGui.QAction(scriptEditor)
        self.spacesToTabs_act.setObjectName(_fromUtf8("spacesToTabs_act"))
        self.settingsFile_act = QtGui.QAction(scriptEditor)
        self.settingsFile_act.setObjectName(_fromUtf8("settingsFile_act"))
        self.editTheme_act = QtGui.QAction(scriptEditor)
        self.editTheme_act.setObjectName(_fromUtf8("editTheme_act"))
        self.menuFile.addAction(self.saveSeccion_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addAction(self.load_act)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit_act)
        self.menuHelp.addAction(self.openManual_act)
        self.menuTools.addAction(self.tabToSpaces_act)
        self.theme_menu.addAction(self.editTheme_act)
        self.theme_menu.addSeparator()
        self.menuOptions.addAction(self.theme_menu.menuAction())
        self.menuOptions.addAction(self.settingsFile_act)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(scriptEditor)
        QtCore.QMetaObject.connectSlotsByName(scriptEditor)

    def retranslateUi(self, scriptEditor):
        scriptEditor.setWindowTitle(_translate("scriptEditor", "MainWindow", None))
        self.executeAll_btn.setText(_translate("scriptEditor", "Execute All", None))
        self.clearHistory_btn.setText(_translate("scriptEditor", "Clear", None))
        self.menuFile.setTitle(_translate("scriptEditor", "File", None))
        self.menuHelp.setTitle(_translate("scriptEditor", "Help", None))
        self.menuTools.setTitle(_translate("scriptEditor", "Tools", None))
        self.menuOptions.setTitle(_translate("scriptEditor", "Options", None))
        self.theme_menu.setTitle(_translate("scriptEditor", "Theme", None))
        self.executeAll_act.setText(_translate("scriptEditor", "Execute All", None))
        self.clearHistory_act.setText(_translate("scriptEditor", "Clear", None))
        self.save_act.setText(_translate("scriptEditor", "Save Script", None))
        self.load_act.setText(_translate("scriptEditor", "Load Script", None))
        self.exit_act.setText(_translate("scriptEditor", "Exit", None))
        self.openManual_act.setText(_translate("scriptEditor", "Open Manual", None))
        self.quickHelp_act.setText(_translate("scriptEditor", "Quick Help", None))
        self.saveSeccion_act.setText(_translate("scriptEditor", "Save session", None))
        self.tabToSpaces_act.setText(_translate("scriptEditor", "Tab to spaces", None))
        self.spacesToTabs_act.setText(_translate("scriptEditor", "Spaces to tab", None))
        self.settingsFile_act.setText(_translate("scriptEditor", "Open Settings Folder", None))
        self.editTheme_act.setText(_translate("scriptEditor", "Edit ...", None))

