# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\tools\pw_scriptEditor\pw_multiScriptEditor\widgets\scriptEditor.ui'
#
# Created: Mon Apr 06 09:46:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_scriptEditor(object):
    def setupUi(self, scriptEditor):
        scriptEditor.setObjectName("scriptEditor")
        scriptEditor.resize(800, 609)
        self.centralwidget = QtGui.QWidget(scriptEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.out_ly = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.out_ly.setContentsMargins(0, 0, 0, 0)
        self.out_ly.setObjectName("out_ly")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.in_ly = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.in_ly.setContentsMargins(0, 0, 0, 0)
        self.in_ly.setObjectName("in_ly")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame_2)
        scriptEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(scriptEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtGui.QMenu(self.menubar)
        self.file_menu.setTearOffEnabled(True)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QtGui.QMenu(self.menubar)
        self.help_menu.setTearOffEnabled(True)
        self.help_menu.setObjectName("help_menu")
        self.tools_menu = QtGui.QMenu(self.menubar)
        self.tools_menu.setTearOffEnabled(True)
        self.tools_menu.setObjectName("tools_menu")
        self.options_menu = QtGui.QMenu(self.menubar)
        self.options_menu.setTearOffEnabled(True)
        self.options_menu.setObjectName("options_menu")
        self.theme_menu = QtGui.QMenu(self.options_menu)
        self.theme_menu.setTearOffEnabled(True)
        self.theme_menu.setObjectName("theme_menu")
        self.run_menu = QtGui.QMenu(self.menubar)
        self.run_menu.setTearOffEnabled(True)
        self.run_menu.setObjectName("run_menu")
        scriptEditor.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(scriptEditor)
        self.toolBar.setObjectName("toolBar")
        scriptEditor.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.clearHistory_act = QtGui.QAction(scriptEditor)
        self.clearHistory_act.setObjectName("clearHistory_act")
        self.save_act = QtGui.QAction(scriptEditor)
        self.save_act.setObjectName("save_act")
        self.load_act = QtGui.QAction(scriptEditor)
        self.load_act.setObjectName("load_act")
        self.exit_act = QtGui.QAction(scriptEditor)
        self.exit_act.setObjectName("exit_act")
        self.openManual_act = QtGui.QAction(scriptEditor)
        self.openManual_act.setObjectName("openManual_act")
        self.quickHelp_act = QtGui.QAction(scriptEditor)
        self.quickHelp_act.setObjectName("quickHelp_act")
        self.saveSeccion_act = QtGui.QAction(scriptEditor)
        self.saveSeccion_act.setObjectName("saveSeccion_act")
        self.tabToSpaces_act = QtGui.QAction(scriptEditor)
        self.tabToSpaces_act.setObjectName("tabToSpaces_act")
        self.spacesToTabs_act = QtGui.QAction(scriptEditor)
        self.spacesToTabs_act.setObjectName("spacesToTabs_act")
        self.settingsFile_act = QtGui.QAction(scriptEditor)
        self.settingsFile_act.setObjectName("settingsFile_act")
        self.editTheme_act = QtGui.QAction(scriptEditor)
        self.editTheme_act.setObjectName("editTheme_act")
        self.shortcuts_act = QtGui.QAction(scriptEditor)
        self.shortcuts_act.setObjectName("shortcuts_act")
        self.donate_act = QtGui.QAction(scriptEditor)
        self.donate_act.setObjectName("donate_act")
        self.about_act = QtGui.QAction(scriptEditor)
        self.about_act.setObjectName("about_act")
        self.execAll_act = QtGui.QAction(scriptEditor)
        self.execAll_act.setObjectName("execAll_act")
        self.execSel_act = QtGui.QAction(scriptEditor)
        self.execSel_act.setObjectName("execSel_act")
        self.copy_act = QtGui.QAction(scriptEditor)
        self.copy_act.setObjectName("copy_act")
        self.cut_act = QtGui.QAction(scriptEditor)
        self.cut_act.setObjectName("cut_act")
        self.paste_act = QtGui.QAction(scriptEditor)
        self.paste_act.setObjectName("paste_act")
        self.find_act = QtGui.QAction(scriptEditor)
        self.find_act.setObjectName("find_act")
        self.undo_act = QtGui.QAction(scriptEditor)
        self.undo_act.setObjectName("undo_act")
        self.redo_act = QtGui.QAction(scriptEditor)
        self.redo_act.setObjectName("redo_act")
        self.printHelp_act = QtGui.QAction(scriptEditor)
        self.printHelp_act.setObjectName("printHelp_act")
        self.comment_cat = QtGui.QAction(scriptEditor)
        self.comment_cat.setObjectName("comment_cat")
        self.file_menu.addAction(self.saveSeccion_act)
        self.file_menu.addAction(self.save_act)
        self.file_menu.addAction(self.load_act)
        self.help_menu.addAction(self.openManual_act)
        self.help_menu.addAction(self.shortcuts_act)
        self.help_menu.addAction(self.donate_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.printHelp_act)
        self.help_menu.addAction(self.about_act)
        self.tools_menu.addAction(self.undo_act)
        self.tools_menu.addAction(self.redo_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.copy_act)
        self.tools_menu.addAction(self.cut_act)
        self.tools_menu.addAction(self.paste_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.tabToSpaces_act)
        self.tools_menu.addAction(self.comment_cat)
        self.tools_menu.addAction(self.find_act)
        self.theme_menu.addAction(self.editTheme_act)
        self.theme_menu.addSeparator()
        self.options_menu.addAction(self.theme_menu.menuAction())
        self.options_menu.addAction(self.settingsFile_act)
        self.run_menu.addAction(self.execAll_act)
        self.run_menu.addAction(self.execSel_act)
        self.run_menu.addAction(self.clearHistory_act)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.run_menu.menuAction())
        self.menubar.addAction(self.options_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.toolBar.addAction(self.execAll_act)
        self.toolBar.addAction(self.execSel_act)
        self.toolBar.addAction(self.clearHistory_act)

        self.retranslateUi(scriptEditor)
        QtCore.QMetaObject.connectSlotsByName(scriptEditor)

    def retranslateUi(self, scriptEditor):
        scriptEditor.setWindowTitle(QtGui.QApplication.translate("scriptEditor", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.file_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.help_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.tools_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.options_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.theme_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "Theme", None, QtGui.QApplication.UnicodeUTF8))
        self.run_menu.setTitle(QtGui.QApplication.translate("scriptEditor", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("scriptEditor", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.clearHistory_act.setText(QtGui.QApplication.translate("scriptEditor", "Clear Output", None, QtGui.QApplication.UnicodeUTF8))
        self.save_act.setText(QtGui.QApplication.translate("scriptEditor", "Save Script", None, QtGui.QApplication.UnicodeUTF8))
        self.load_act.setText(QtGui.QApplication.translate("scriptEditor", "Load Script", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_act.setText(QtGui.QApplication.translate("scriptEditor", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.openManual_act.setText(QtGui.QApplication.translate("scriptEditor", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.quickHelp_act.setText(QtGui.QApplication.translate("scriptEditor", "Quick Help", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSeccion_act.setText(QtGui.QApplication.translate("scriptEditor", "Save session", None, QtGui.QApplication.UnicodeUTF8))
        self.tabToSpaces_act.setText(QtGui.QApplication.translate("scriptEditor", "Tab to spaces", None, QtGui.QApplication.UnicodeUTF8))
        self.spacesToTabs_act.setText(QtGui.QApplication.translate("scriptEditor", "Spaces to tab", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsFile_act.setText(QtGui.QApplication.translate("scriptEditor", "Open Settings Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.editTheme_act.setText(QtGui.QApplication.translate("scriptEditor", "Edit ...", None, QtGui.QApplication.UnicodeUTF8))
        self.shortcuts_act.setText(QtGui.QApplication.translate("scriptEditor", "Show Shortcuts", None, QtGui.QApplication.UnicodeUTF8))
        self.donate_act.setText(QtGui.QApplication.translate("scriptEditor", "Donate", None, QtGui.QApplication.UnicodeUTF8))
        self.about_act.setText(QtGui.QApplication.translate("scriptEditor", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.execAll_act.setText(QtGui.QApplication.translate("scriptEditor", "Execute All", None, QtGui.QApplication.UnicodeUTF8))
        self.execSel_act.setText(QtGui.QApplication.translate("scriptEditor", "Execute Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_act.setText(QtGui.QApplication.translate("scriptEditor", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.cut_act.setText(QtGui.QApplication.translate("scriptEditor", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.paste_act.setText(QtGui.QApplication.translate("scriptEditor", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.find_act.setText(QtGui.QApplication.translate("scriptEditor", "Find and Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.undo_act.setText(QtGui.QApplication.translate("scriptEditor", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.redo_act.setText(QtGui.QApplication.translate("scriptEditor", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.printHelp_act.setText(QtGui.QApplication.translate("scriptEditor", "Print Help", None, QtGui.QApplication.UnicodeUTF8))
        self.comment_cat.setText(QtGui.QApplication.translate("scriptEditor", "Comment", None, QtGui.QApplication.UnicodeUTF8))

