syntax = {"extension": [
            "py", "pyw"],

          "comment": ["#"],

          "string": ["\"", "'"],

          "operators": ["=",
                        # Comparison
                        "!=", "<", ">",
                        # Arithmetic
                        "+", "\-", "*", "/", "%", "*",
                        # Bitwise
                        "^", "|", "&"],
          "keywords": [ "and",
                        "assert",
                        "break",
                        "continue",
                        "del",
                        "elif",
                        "else",
                        "except",
                        "exec",
                        "finally",
                        "for",
                        "from",
                        "global",
                        "if",
                        "import",
                        "in",
                        "is",
                        "not",
                        "or",
                        "pass",
                        "print",
                        "raise",
                        "return",
                        "try",
                        "while",
                        "yield",
                        "None",
                        "with"
                        ],
          "definition":["class",
                        "def",
                        "lambda"],
          "boolean" : ["True",
                        "False"],
          "extras": [
                    "abs",
                    "all",
                    "any",
                    "basestring",
                    "bin",
                    "bool",
                    "bytearray",
                    "callable",
                    "chr",
                    "classmethod",
                    "cmp",
                    "compile",
                    "complex",
                    "delattr",
                    "dict",
                    "dir",
                    "divmod",
                    "enumerate",
                    "eval",
                    "execfile",
                    "file",
                    "filter",
                    "float",
                    "format",
                    "frozenset",
                    "getattr",
                    "globals",
                    "hasattr",
                    "hash",
                    "help",
                    "hex",
                    "id",
                    "input",
                    "int",
                    "isinstance",
                    "issubclass",
                    "iter",
                    "len",
                    "list",
                    "locals",
                    "long",
                    "map",
                    "max",
                    "memoryview",
                    "min",
                    "next",
                    "object",
                    "oct",
                    "open",
                    "ord",
                    "pow",
                    "property",
                    "range",
                    "raw_input",
                    "reduce",
                    "reload",
                    "repr",
                    "reversed",
                    "round",
                    "set",
                    "setattr",
                    "slice",
                    "sorted",
                    "staticmethod",
                    "str",
                    "sum",
                    "tuple",
                    "type",
                    "unichr",
                    "unicode",
                    "vars",
                    "xrange",
                    "zip",
                    "apply",
                    "buffer",
                    "coerce",
                    "intern"
                  ],
          "braces" :['\{', '\}', '\(', '\)', '\[', '\]']

}

